development:
  adapter: postgresql
  encoding: unicode
  database: mdm_development
  pool: 5
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: mdm_test
  pool: 5
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
